name: Update Silver Price Plot

on:
  schedule:
    - cron: '0 22 * * *'  # Runs daily at 22:00 UTC

jobs:
  update-plot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib yfinance

    - name: Generate plot
      run: python generate_plot.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add static/imgforblogposts/post35/silver_price_plot.png
        git commit -m 'Update Silver price plot'
        git push
